### ISSUE TITLE
Can't address email in Gmail with RightTasks for Gmail enabled

### ISSUE THREAD

**Issue by taskdaynite** [ghinda/righttasks#15]
When I used RightTasks for Gmail I'm unable to compose a new message in Gmail. Specifically, I can't address a message: Typing in the TO line is disabled. I can't type in the subject line or in the body of the message. 

This is a consistent problem. Usually after I re-enable RightTasks everything works fine for a hour or so; the the problem happens and I'm not able to type anything in a newly created message until I turn off RightTasks again.

I'm using Chrome and Windows 7.

**Comment by ghinda** [comment]
Sorry to address this so late. I can't replicate you're having.

If you're still using righttasks, does this happen with the latest version? Are you using other extensions that interact with Gmail?
