### ISSUE TITLE
Feature request: Multiple vertical task lists

### ISSUE THREAD

**Issue by robertandrews** [ghinda/righttasks#25]
I sometimes run Gmail in Chrome on a large iMac screen with plenty of real estate. I also keep multiple task lists.

Placing a single task list on the right-hand side of Gmail is great, but most of the vertical space is blank. The space could accommodate multiple of my task lists, stacked vertically.

**Comment by ghinda** [comment]
I'm going to consider it for the next version that will probably launch sometime early next year.

You can sign up here and I'll let you know when it launches:
http://www.righttasks.com/
