### ISSUE TITLE
Different Task List Settings for Different Email Addresses

### ISSUE THREAD

**Issue by brianazick** [ghinda/righttasks#28]
I use multiple email addresses in the same browser at the same time, but do not use tasks on all of them. However, when I minimize or maximize the vertical task bar in one tab, it performs the same action in all other tabs upon refresh. Would it be possible to allow for different settings for separate email addresses?

**Comment by ghinda** [comment]
Thanks for the suggestion. I'll see if I can implement it for the current version.

Also, keep an eye on the upcoming version that will surely support it http://www.righttasks.com/.
