### ISSUE TITLE
Feature Request: Remember the user's Task Panel collapse state

### ISSUE THREAD

**Issue by ltgs** [ghinda/righttasks#31]
The panel takes up a lot of room on my laptop and I only want it open when tending to my tasks. So most of the time when I want to do email, I have to keep manually closing the task panel, which gets cumbersome. But sometimes I might be working on my tasks, and want to keep it open. How about remembering the last state (open or collapsed)?

**Comment by ghinda** [comment]
Implemented in the latest version.

**Comment by ltgs** [comment]
Great news! Thank you
